using Content.Client.UserInterface.Controls;
using Content.Shared.DeadSpace.CoordinatePortal;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Timing;

namespace Content.Client.DeadSpace.CoordinatePortal.UI;

[GenerateTypedNameReferences]
public sealed partial class CoordinatePortalConsoleWindow : FancyWindow
{
    private const int MaxCoordinateDistance = 3048;

    private readonly IGameTiming _timing;

    private CoordinatePortalConsoleBoundUserInterfaceState? _state;
    private bool _updating;

    public event Action<int, int>? SetTarget;
    public event Action<int, int>? TogglePortal;

    public CoordinatePortalConsoleWindow()
    {
        RobustXamlLoader.Load(this);

        _timing = IoCManager.Instance!.Resolve<IGameTiming>();

        StatusPanel.PanelOverride = new StyleBoxFlat
        {
            BackgroundColor = Color.FromHex("#141820"),
            BorderColor = Color.FromHex("#2aa6b8"),
            BorderThickness = new Thickness(1)
        };

        TargetPanel.PanelOverride = new StyleBoxFlat
        {
            BackgroundColor = Color.FromHex("#17151f"),
            BorderColor = Color.FromHex("#9b5bb8"),
            BorderThickness = new Thickness(1)
        };

        CooldownBar.ForegroundStyleBoxOverride = new StyleBoxFlat(Color.FromHex("#2aa6b8"));

        TargetX.InitDefaultButtons();
        TargetY.InitDefaultButtons();
        TargetX.LineEditControl.IsValid = IsCoordinateInputValid;
        TargetY.LineEditControl.IsValid = IsCoordinateInputValid;

        UseCurrentButton.OnPressed += _ => UseCurrentCoordinates();
        SetTargetButton.OnPressed += _ =>
        {
            var (x, y) = ClampTargetInputs();
            SetTarget?.Invoke(x, y);
        };
        TogglePortalButton.OnPressed += _ =>
        {
            var (x, y) = ClampTargetInputs();
            TogglePortal?.Invoke(x, y);
        };

        TargetX.ValueChanged += _ => OnTargetValueChanged();
        TargetY.ValueChanged += _ => OnTargetValueChanged();
    }

    public void UpdateState(CoordinatePortalConsoleBoundUserInterfaceState state)
    {
        _state = state;
        SetTargetValues(state.TargetX, state.TargetY);
        ClampTargetInputs();

        LocalPositionLabel.Text = Loc.GetString("coordinate-portal-current-position",
            ("x", ToUiCoordinate(state.CurrentX)),
            ("y", ToUiCoordinate(state.CurrentY)));

        RefreshControls();
    }

    protected override void FrameUpdate(FrameEventArgs args)
    {
        base.FrameUpdate(args);
        RefreshControls();
    }

    private void UseCurrentCoordinates()
    {
        if (_state == null)
            return;

        SetTargetValues(_state.CurrentX, _state.CurrentY);
        var (x, y) = ClampTargetInputs();
        SetTarget?.Invoke(x, y);
    }

    private void OnTargetValueChanged()
    {
        if (!_updating)
            ClampTargetInputs();

        RefreshControls();
    }

    private void RefreshControls()
    {
        if (_updating || _state == null)
            return;

        var validInputs = InputsValid();
        var remaining = _state.NextReady - _timing.CurTime;
        var coolingDown = !_state.Active && remaining > TimeSpan.Zero;

        if (_state.Active)
        {
            StatusValue.Text = Loc.GetString("coordinate-portal-status-active");
            StatusValue.ModulateSelfOverride = Color.FromHex("#70f3ff");
            CooldownBar.Value = 1f;
            CooldownText.Text = "00:00";
            TogglePortalButton.Text = Loc.GetString("coordinate-portal-close-button");
        }
        else if (coolingDown)
        {
            StatusValue.Text = Loc.GetString("coordinate-portal-status-cooldown");
            StatusValue.ModulateSelfOverride = Color.FromHex("#d6a8ff");
            CooldownBar.Value = _state.Cooldown == TimeSpan.Zero
                ? 1f
                : Math.Clamp(1f - (float) (remaining.TotalSeconds / _state.Cooldown.TotalSeconds), 0f, 1f);
            CooldownText.Text = $"{remaining.Minutes:00}:{remaining.Seconds:00}";
            TogglePortalButton.Text = Loc.GetString("coordinate-portal-open-button");
        }
        else if (!_state.Powered || !_state.HasCoordinateParent)
        {
            StatusValue.Text = Loc.GetString("coordinate-portal-status-offline");
            StatusValue.ModulateSelfOverride = Color.FromHex("#ff7676");
            CooldownBar.Value = 0f;
            CooldownText.Text = "--:--";
            TogglePortalButton.Text = Loc.GetString("coordinate-portal-open-button");
        }
        else
        {
            StatusValue.Text = Loc.GetString("coordinate-portal-status-ready");
            StatusValue.ModulateSelfOverride = Color.FromHex("#78ffa8");
            CooldownBar.Value = 1f;
            CooldownText.Text = "00:00";
            TogglePortalButton.Text = Loc.GetString("coordinate-portal-open-button");
        }

        var inputDisabled = _state.Active || !_state.Powered;
        UseCurrentButton.Disabled = inputDisabled || !_state.HasCoordinateParent;
        SetTargetButton.Disabled = inputDisabled || !validInputs || !_state.HasCoordinateParent;
        TogglePortalButton.Disabled = !_state.Powered ||
                                      !_state.HasCoordinateParent ||
                                      (!validInputs && !_state.Active) ||
                                      coolingDown;
    }

    private bool InputsValid()
    {
        return int.TryParse(TargetX.LineEditControl.Text, out _) &&
               int.TryParse(TargetY.LineEditControl.Text, out _);
    }

    private static bool IsCoordinateInputValid(string text)
    {
        return text is "" or "-" or "+" || int.TryParse(text, out _);
    }

    private (int X, int Y) ClampTargetInputs()
    {
        if (_state == null)
        {
            var fallbackX = TargetX.Value;
            var fallbackY = TargetY.Value;
            SetTargetValues(fallbackX, fallbackY);
            return (fallbackX, fallbackY);
        }

        var x = ClampTargetCoordinate(TargetX.Value, _state.CurrentX);
        var y = ClampTargetCoordinate(TargetY.Value, _state.CurrentY);
        SetTargetValues(x, y);
        return (x, y);
    }

    private static int ClampTargetCoordinate(int value, float current)
    {
        var min = ToUiCoordinate(current - MaxCoordinateDistance);
        var max = ToUiCoordinate(current + MaxCoordinateDistance);
        return Math.Clamp(value, min, max);
    }

    private void SetTargetValues(float x, float y)
    {
        _updating = true;
        TargetX.Value = ToUiCoordinate(x);
        TargetY.Value = ToUiCoordinate(y);
        _updating = false;
    }

    private static int ToUiCoordinate(float value)
    {
        return (int) MathF.Round(value, MidpointRounding.AwayFromZero);
    }
}
